import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import './index.css';
import { RouterProvider } from "react-router-dom";
import router from "../src/Routes/routes";
import App from "../src/App";
import { Provider } from "react-redux";
import Store from "./redux/store";
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsxs(Provider, { store: Store, children: [_jsx(RouterProvider, { router: router }), _jsx(App, {})] }) }));
